(async () => {
  try {
    //
  } catch (e) {
    console.log('an error occurred', e);
  }
})();
